force-app/PackagingWizard/main/core/objects/PackagingWizardSettings__c/PackagingWizardSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Packaging Wizard Settings</label>
</CustomObject>

force-app/PackagingWizard/main/core/objects/PackagingWizardSettings__c/fields/ManagedPackagePrefix__c.field-meta.xml
<CustomField>
    <fullName>ManagedPackagePrefix__c</fullName>
    <label>Managed Package Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/PackagingWizard/main/core/objects/PackagingWizardSettings__c/fields/PackageName__c.field-meta.xml
<CustomField>
    <fullName>PackageName__c</fullName>
    <label>Package Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/PackagingWizard/main/core/objects/SalesforceOrgCredentials__c/SalesforceOrgCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Salesforce Org Credentials</label>
</CustomObject>

force-app/PackagingWizard/main/core/objects/SalesforceOrgCredentials__c/fields/IsSandbox__c.field-meta.xml
<CustomField>
    <fullName>IsSandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/PackagingWizard/main/core/objects/SalesforceOrgCredentials__c/fields/SecurityToken__c.field-meta.xml
<CustomField>
    <fullName>SecurityToken__c</fullName>
    <label>Security Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/PackagingWizard/main/core/objects/SalesforceOrgCredentials__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>User Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/PackagingWizard/main/core/classes/data/SalesforceOrgsData.cls
public inherited sharing class SalesforceOrgsData {
    
    public static final String ORG_DEVHUB = 'devhub';
    public static final String ORG_QA = 'qa';
    public static final String ORG_STAGING = 'staging';

    public static final List<String> ORGS = new List<String>{
        ORG_DEVHUB, ORG_QA, ORG_STAGING
    };

    public static SalesforceOrgCredentials__c getCredentialsByOrgName(String orgName) {
        return SalesforceOrgCredentials__c.getInstance(orgName.toLowerCase());
    }

    public static Map<String, SalesforceOrgCredentials__c> getAllOrgsCredentials() {
        return SalesforceOrgCredentials__c.getAll();
    }

    public static void storeCredentialsForOrg(
        String orgName, String username, String password, String token, Boolean isSandbox
    ) {
        orgName = orgName.toLowerCase();
        SalesforceOrgCredentials__c creds = getCredentialsByOrgName(orgName);
        if (creds == null) {
            creds = new SalesforceOrgCredentials__c(Name = orgName);
        }
        creds.Username__c = username;
        creds.Password__c = password; 
        creds.SecurityToken__c = token; 
        creds.IsSandbox__c = isSandbox;
        upsert creds;
    }

    public static void deleteCredentialsForOrg(String orgName) {
        SalesforceOrgCredentials__c creds = getCredentialsByOrgName(orgName);
        if (creds != null) {
            delete creds;
        }
    }

    public static String getManagedPackagePrefix() { 
        PackagingWizardSettings__c setts = PackagingWizardSettings__c.getOrgDefaults();
        return (setts != null) ? setts.ManagedPackagePrefix__c : null;
    }

    public static void setManagedPackagePrefix(String managedPackagePrefix) { 
        PackagingWizardSettings__c setts = PackagingWizardSettings__c.getOrgDefaults();
        if (setts != null && setts.Id != null) {
            setts.ManagedPackagePrefix__c = managedPackagePrefix;
            update setts;
        } else {
            insert new PackagingWizardSettings__c(
                ManagedPackagePrefix__c = managedPackagePrefix
            );
        }
    }

    public static String getPackageName() { 
        PackagingWizardSettings__c setts = PackagingWizardSettings__c.getOrgDefaults();
        return (setts != null) ? setts.PackageName__c : null;
    }

    public static void setPackageName(String packageName) { 
        PackagingWizardSettings__c setts = PackagingWizardSettings__c.getOrgDefaults();
        if (setts != null && setts.Id != null) {
            setts.PackageName__c = packageName;
            update setts;
        } else {
            insert new PackagingWizardSettings__c(
                PackageName__c = packageName
            );
        }
    }

}